version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepassword
      POSTGRES_DB: exampledb
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: ./api
    restart: always
    environment:
      DB_HOST: db
      DB_USER: exampleuser
      DB_PASSWORD: examplepassword
      DB_NAME: exampledb
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./api:/usr/src/api

volumes:
  db_data: